CREATE PROCEDURE releaseSemaphoreLock(IN tokenIn VARCHAR(256))
    MODIFIES SQL DATA
    SQL SECURITY INVOKER
BEGIN
	UPDATE SEMAPHORE_LOCK SET TOKEN = NULL, CONTEXT = NULL WHERE TOKEN = tokenIn;
	SELECT ROW_COUNT() AS RESULT;
END