CREATE PROCEDURE releaseSemaphoreLock(IN tokenIn VARCHAR(256))
    MODIFIES SQL DATA
    SQL SECURITY INVOKER
BEGIN
	SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
	START TRANSACTION;
	UPDATE SEMAPHORE_LOCK SET TOKEN = NULL WHERE TOKEN = tokenIn;
	SELECT ROW_COUNT() AS RESULT;
	COMMIT;
END