CREATE TABLE IF NOT EXISTS `WRITE_READ_MASTER` (
    `LOCK_KEY` varchar(256)CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
    `WRITE_LOCK_TOKEN` varchar(256)CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `PRECURSOR_TOKEN` varchar(256)CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `EXPIRES_ON` TIMESTAMP NULL,
    PRIMARY KEY (`LOCK_KEY`),
    UNIQUE KEY (`WRITE_LOCK_TOKEN`),
    UNIQUE KEY (`PRECURSOR_TOKEN`)
);