# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  mysql_database: semaphore
  mysql_user: azurediamond
  mysql_password: hunter2
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup MySQL
      # You may pin to the exact commit or the version.
      # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
      uses: mirromutth/mysql-action@v1.1
      with:
        # Version of MySQL to use
        mysql version: 8.0.31
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: ${{ env.mysql_database }}
        # MYSQL_USER - create the specified user with superuser power for created database
        mysql user: ${{ env.mysql_user }}
        # MYSQL_PASSWORD - specified superuser password which user is power for created database
        mysql password: ${{ env.mysql_password }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Djdbc.url=jdbc:mysql://localhost/${{ env.mysql_database }} -Djdbc.username=${{ env.mysql_user }} -Djdbc.password=${{ env.mysql_password }}
